[build]
  publish = "dist"

[[redirects]]
  from = "/:param"  # Match any path with a parameter
  to = "https://shrinkle-be.netlify.app/:param" # Replace with your actual backend site's Netlify domain
  status = 200